// Mock products data for development
export const mockProducts = [
  {
    _id: "1",
    id: "1",
    title: "ABB Variable Frequency Drive ACS580",
    description: "High-performance variable frequency drive for HVAC applications. Energy-efficient motor control with advanced features.",
    price: 1250.00,
    category: "hvac",
    brand: "ABB",
    image: "https://images.unsplash.com/photo-1562408590-e32931084e23?w=400&h=300&fit=crop&crop=center&auto=format&q=75",
    stock: 15,
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "2",
    id: "2",
    title: "FGV Ball Valve DN50",
    description: "High-quality brass ball valve with full port design. Suitable for water, oil, and gas applications.",
    price: 125.00,
    category: "valves",
    brand: "FGV",
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&crop=center&auto=format&q=75",
    stock: 25,
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "3",
    id: "3",
    title: "Kitz Gate Valve",
    description: "Premium stainless steel gate valve for industrial applications. Corrosion-resistant and long-lasting.",
    price: 185.00,
    category: "valves",
    brand: "Kitz",
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400&h=300&fit=crop&crop=center&auto=format&q=75",
    stock: 18,
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "4",
    id: "4",
    title: "WALTHER-WERKE Industrial Connector",
    description: "Heavy-duty electrical connector for industrial applications. IP67 rated for harsh environments.",
    price: 95.00,
    category: "electrical",
    brand: "WALTHER-WERKE",
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=300&fit=crop&crop=center&auto=format&q=75",
    stock: 30,
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "5",
    id: "5",
    title: "nVent Hoffman Enclosure",
    description: "NEMA 4X stainless steel enclosure for harsh environments. Perfect for industrial control systems.",
    price: 450.00,
    category: "electrical",
    brand: "nVent Hoffman",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop&crop=center&auto=format&q=75",
    stock: 12,
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "6",
    id: "6",
    title: "Grundfos Circulation Pump",
    description: "Energy-efficient circulation pump for HVAC and plumbing systems. Variable speed control included.",
    price: 680.00,
    category: "plumbing",
    brand: "Grundfos",
    image: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400&h=300&fit=crop&crop=center&auto=format&q=75",
    stock: 8,
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "7",
    id: "7",
    title: "Industrial Pipe Fitting Set",
    description: "Complete set of stainless steel pipe fittings for industrial plumbing applications.",
    price: 220.00,
    category: "plumbing",
    brand: "Frazer",
    image: "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=400&h=300&fit=crop&crop=center&auto=format&q=75",
    stock: 20,
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    _id: "8",
    id: "8",
    title: "High-Temperature Adhesive",
    description: "Industrial-grade high-temperature adhesive for extreme conditions up to 300°C.",
    price: 75.00,
    category: "adhesives",
    brand: "3M",
    image: "https://images.unsplash.com/photo-1580374411072-4925b4fd0a1c?w=400&h=300&fit=crop&crop=center&auto=format&q=75",
    stock: 35,
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date()
  }
];
